# Generated by Django 5.1.4 on 2026-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color identificativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Fisioterapeuta',
                'verbose_name_plural': 'Fisioterapeutas',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
