# Generated by Django 5.1.4 on 2026-04-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Número de bono')),
                ('bonus_type', models.IntegerField(choices=[(5, '5 sesiones'), (10, '10 sesiones')], verbose_name='Tipo de bono')),
                ('sessions_used', models.PositiveIntegerField(default=0, verbose_name='Sesiones consumidas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['-created_at'],
            },
        ),
    ]
