# Generated by Django 5.1.4 on 2026-04-22 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_issued', models.BooleanField(default=False, verbose_name='Factura emitida')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de factura')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Importe (€)')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Es de bono')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('bizum', 'Bizum'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('treatment_type', models.CharField(choices=[('avanzada', 'Avanzada'), ('general', 'General'), ('ondas', 'Ondas de choque'), ('dinamo', 'Dinamo'), ('emg', 'EMG'), ('propio', 'Paciente propio'), ('sabado', 'Sábado'), ('informe', 'Informe'), ('domicilio', 'A domicilio'), ('bono', 'De bono')], max_length=20, verbose_name='Tipo de tratamiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Pagado')),
                ('fisio_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Importe fisioterapeuta (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='bonuses.bonus', verbose_name='Bono')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='patients.patient', verbose_name='Paciente')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FisioRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('avanzada', 'Avanzada'), ('general', 'General'), ('ondas', 'Ondas de choque'), ('dinamo', 'Dinamo'), ('emg', 'EMG'), ('propio', 'Paciente propio'), ('sabado', 'Sábado'), ('informe', 'Informe'), ('domicilio', 'A domicilio'), ('bono', 'De bono')], max_length=20, verbose_name='Tipo de tratamiento')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Es de bono')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tarifa (€)')),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta')),
            ],
            options={
                'verbose_name': 'Tarifa de fisioterapeuta',
                'verbose_name_plural': 'Tarifas de fisioterapeutas',
                'unique_together': {('fisio', 'treatment_type', 'is_bonus')},
            },
        ),
    ]
