# Generated by Django 5.1.4 on 2026-04-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0002_physio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisiorate',
            name='fisio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='users.physio', verbose_name='Fisioterapeuta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='users.physio', verbose_name='Trabajador'),
        ),
    ]
