# Generated by Django 5.1.4 on 2026-05-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_fisiorate_fisio_alter_sale_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinatario')),
                ('body', models.TextField(verbose_name='Cuerpo de la factura')),
                ('issued_at', models.DateField(verbose_name='Fecha de emisión')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Último envío por email')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
