# Generated by Django 5.1.4 on 2026-05-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_paid',
        ),
    ]
